### ISSUE TITLE
Please indicate the source of the codebase in your README file

### ISSUE THREAD

**Issue by caiyuanhao1998** [caizeyu1992/SST#1]
Hi, Thanks for your good work. I notice that this repo is based on my [MST](https://github.com/caiyuanhao1998/MST). So, please indicate this in your README file, thanks.

麻烦注明一下代码来源和出处，谢谢。

**Comment by xintangjin** [comment]
感谢大佬提醒，之前引用了，最近paper投稿，内容都删了，忘记修改了。感谢感谢

**Comment by caiyuanhao1998** [comment]
我是说这个git repo的readme。

**Comment by xintangjin** [comment]
刚修改了，您看下可以吗

**Comment by xintangjin** [comment]
大佬，有机会还请指导指导，感谢感谢！

**Comment by caiyuanhao1998** [comment]
挺好的，感谢感谢，之前朋友在CVPR审到过这篇文章，给的接收。后边结果怎么样了？

**Comment by xintangjin** [comment]
谢谢大佬关注，太感谢了。之前的cvpr被拒了，分数惨不忍睹，导师压着改到现在，目前是准备投期刊了，可能近期会投出去。再次感谢，最近忙的头晕，竟然把最重要的致谢搞忘了，下次我一定注意。thanks,thanks,有问题的话，我到时候邮件请教您。

**Comment by caiyuanhao1998** [comment]
好的，加油加油，这篇文章质量很棒，再好好改改肯定没问题的。

**Comment by xintangjin** [comment]
好的，谢谢大佬，向大佬学习，再次感谢大佬能够提供这么优秀的作品。
